spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/offer
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true       # hibernate가 만들어준 sql을 로그에 표시
        use_sql_comments: true # sql문 주석으로 추가하여 표시해줌

logging.level:
  org.hibernate.SQL: debug
